# Generated by Django 5.1.4 on 2024-12-26 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_rename_save_saveitem_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashtag_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hashtag_ru',
        ),
    ]
