# Generated by Django 5.1.4 on 2024-12-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0003_remove_post_hashtag_en_remove_post_hashtag_ru'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
    ]
