# Generated by Django 5.1.4 on 2024-12-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0004_alter_commentlike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
